version: '3'
services: 
  nginx:
    image: byappt/nginx
    container_name: byappt_nginx
    volumes: 
      - /usr/local/var/www:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /usr/local/etc/ssl:/etc/ssl
    ports: 
      - "80:80"
      - "443:443"
  video:
    image: byappt/video 
    container_name: byappt_video
    env_file: /usr/local/etc/byappt/twilio.env
    expose: 
      - "3001"
  